ARG BUILD_FROM=ghcr.io/hassio-addons/base-python/amd64:stable
FROM ${BUILD_FROM}

# Set shell
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apk add --no-cache py3-pip
RUN pip3 install --break-system-packages --no-cache-dir --upgrade \
    paho-mqtt==1.6.1 \
    requests==2.31.0

# Copy data for add-on
COPY . .

RUN printenv

ARG FIMPSERVER
ARG FIMPUSERNAME
ARG FIMPPASSWORD
ARG FIMPPORT
ARG CLIENT_ID
ARG DEBUG
ARG SELECTED_DEVICES

ENV FIMPSERVER $FIMPSERVER
ENV FIMPUSERNAME $FIMPUSERNAME
ENV FIMPPASSWORD $FIMPPASSWORD
ENV FIMPPORT $FIMPPORT
ENV CLIENT_ID $CLIENT_ID
ENV DEBUG $DEBUG
ENV SELECTED_DEVICES $SELECTED_DEVICES

RUN printenv

RUN chmod a+x run.sh

CMD [ "/run.sh" ]
