ARG BUILD_FROM=ghcr.io/hassio-addons/base-python/amd64:stable
FROM ${BUILD_FROM}

# Set shell
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ARG FIMPSERVER
ENV FIMPSERVER=$FIMPSERVER
ARG FIMPUSERNAME
ENV FIMPUSERNAME=$FIMPUSERNAME
ARG FIMPPASSWORD
ENV FIMPPASSWORD=$FIMPPASSWORD
ARG FIMPPORT
ENV FIMPPORT=$FIMPPORT
ARG CLIENT_ID
ENV CLIENT_ID=$CLIENT_ID
ARG DEBUG
ENV DEBUG=$DEBUG
ARG SELECTED_DEVICES
ENV SELECTED_DEVICES=$SELECTED_DEVICES

RUN apk add --no-cache py3-pip
RUN pip3 install --break-system-packages --no-cache-dir --upgrade \
    paho-mqtt==1.6.1 \
    requests==2.31.0

# Copy data for add-on
COPY . .

RUN chmod a+x run.sh

CMD [ "/run.sh" ]
