

UOM_LUX = "lx"
UOM_PERCENTAGE = "%"
UOM_TEMPERATURE = "°C"
UOM_ENERGY = "kWh"
UOM_POWER = "W"

STATE_CLASS_INCREASING = "total_increasing"
STATE_CLASS_MEASUREMENT = "measurement"

DEVICE_CLASS_ENERGY = "energy"
DEVICE_CLASS_POWER = "power"